### ISSUE TITLE
Support non-optimized builds on pure wasm backend

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/rust-wasm#1]
Currently, compilation tends to go awry if you use `wasm32-unknown-unknown` without optimizations enabled. This is essentially due to immaturity of the rest of the toolchain; this issue is just for tracking the status.

**Comment by alexcrichton** [comment]
I believe at least one piece in solving this will be https://github.com/aturon/rust-wasm/issues/3. If you leave LLVM assertions turned on then at lower optimization levels it often hits an LLVM assertion. There *may* also be bugs in binaryen's s2wasm right now, but I don't think we've ever gotten far enough to test that.

We shouldn't close this out automatically with #3 though because it's likely we'll need to do more than just upgrade llvm.

**Comment by alexcrichton** [comment]
Since upgrading to LLVM 6 this is unfortunately still not fixed, and I've started closing bugs in favor of https://github.com/rust-lang/rust/issues/46367 which I plan to use as the rustc tracking issue for this.

**Comment by alexcrichton** [comment]
Initial testing shows that https://github.com/rust-lang-nursery/rust-wasm/issues/2 plus https://github.com/rust-lang-nursery/rust-wasm/issues/3 will solve this issue. Once those are in-tree though we should go through all the linked test cases on https://github.com/rust-lang/rust/issues/46367 and make sure they work.

**Comment by alexcrichton** [comment]
With #2 and #3 now landed, I believe this works!
