### ISSUE TITLE
Deterministic builds

### ISSUE THREAD

**Issue by pepyakin** [rust-lang-nursery/rust-wasm#93]
Is it reasonable to expect that `rustc` will generate same wasm binaries (i.e. byte-to-byte) for same source inputs on every invocation on every host platform?

cc @alexcrichton

**Comment by est31** [comment]
Right now that is not the case at least because of panic information storing the full path... only the panic printer omits the components before the file. You can turn this off though IIRC with an option. Otherwise there is https://github.com/rust-lang/rust/issues/34902 to track deterministic builds.

**Comment by alexcrichton** [comment]
A good question! Builds should in theory be as deterministic as other platforms like OSX/Linux/Windows. We certainly expect them to be deterministic to the best degree possible, and if there's any reason they aren't I think we'd definitely consider it a bug! Even across multiple OS-es I think we can and definitely should strive to have it be byte-for-byte reproducible for wasm.

If anything comes up where it's not though feel free to open an issue on rust-lang/rust!
